name: Tag-Bump
on:
  push:
    branches:
      - main
jobs:
  ## tag
  tag-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: "true"
          version-file: "./.version"
          tag-prefix: ""
      - name: Extract tag version
        id: extract-tag-version
        run: echo "TAG_VERSION=$(echo ${{ steps.changelog.outputs }})" >> $GITHUB_ENV

      - name: Update version file
        run: echo "${{ env.TAG_VERSION }}" > .version
