name: Automate Tags
on:
  push:
    branches:
      - main
jobs:
  #This job will bump tag number based on the (conventional) commit message.
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "./version.json"
          version-path: "version"
          tag-prefix: ""
          release-count: 0
